# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.2.dev11+g3c66783.d20230603'
__version_tuple__ = version_tuple = (0, 2, 2, 'dev11', 'g3c66783.d20230603')
